"""rename department

Revision ID: 100633756660
Revises: 7ecd1f97cff0
Create Date: 2024-07-17 22:53:20.992016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100633756660'
down_revision = '7ecd1f97cff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
