"""rename address

Revision ID: 825fd8080415
Revises: 100633756660
Create Date: 2024-07-17 22:56:02.600071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825fd8080415'
down_revision = '100633756660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
